// @generated by buffa-codegen. DO NOT EDIT.
// source: perf.proto

#[derive(Clone, PartialEq, Default)]
pub struct Tile {
    /// Field 1: `features`
    pub features: ::buffa::alloc::vec::Vec<Feature>,
}
impl ::core::fmt::Debug for Tile {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Tile").field("features", &self.features).finish()
    }
}
impl Tile {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/perf.Tile";
}
impl ::buffa::DefaultInstance for Tile {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<Tile> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for Tile {
    const PACKAGE: &'static str = "perf";
    const NAME: &'static str = "Tile";
    const FULL_NAME: &'static str = "perf.Tile";
    const TYPE_URL: &'static str = "type.googleapis.com/perf.Tile";
}
impl ::buffa::Message for Tile {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        for v in &self.features {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.features {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                let mut elem = ::core::default::Default::default();
                ::buffa::Message::merge_length_delimited(&mut elem, buf, depth)?;
                self.features.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, depth)?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.features.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Feature {
    /// Field 1: `values`
    pub values: ::buffa::alloc::vec::Vec<u32>,
}
impl ::core::fmt::Debug for Feature {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Feature").field("values", &self.values).finish()
    }
}
impl Feature {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/perf.Feature";
}
impl ::buffa::DefaultInstance for Feature {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<Feature> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for Feature {
    const PACKAGE: &'static str = "perf";
    const NAME: &'static str = "Feature";
    const FULL_NAME: &'static str = "perf.Feature";
    const TYPE_URL: &'static str = "type.googleapis.com/perf.Feature";
}
impl ::buffa::Message for Feature {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.values.is_empty() {
            let payload: u32 = self
                .values
                .iter()
                .map(|&v| ::buffa::types::uint32_encoded_len(v) as u32)
                .sum::<u32>();
            size
                += 1u32 + ::buffa::encoding::varint_len(payload as u64) as u32 + payload;
        }
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.values.is_empty() {
            let payload: u32 = self
                .values
                .iter()
                .map(|&v| ::buffa::types::uint32_encoded_len(v) as u32)
                .sum::<u32>();
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(payload as u64, buf);
            for &v in &self.values {
                ::buffa::types::encode_uint32(v, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() == ::buffa::encoding::WireType::LengthDelimited {
                    let len = ::buffa::encoding::decode_varint(buf)?;
                    let len = usize::try_from(len)
                        .map_err(|_| ::buffa::DecodeError::MessageTooLarge)?;
                    if buf.remaining() < len {
                        return ::core::result::Result::Err(
                            ::buffa::DecodeError::UnexpectedEof,
                        );
                    }
                    self.values.reserve(len);
                    let mut limited = buf.take(len);
                    while limited.has_remaining() {
                        self.values.push(::buffa::types::decode_uint32(&mut limited)?);
                    }
                    let leftover = limited.remaining();
                    if leftover > 0 {
                        limited.advance(leftover);
                    }
                } else if tag.wire_type() == ::buffa::encoding::WireType::Varint {
                    self.values.push(::buffa::types::decode_uint32(buf)?);
                } else {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, depth)?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.values.clear();
    }
}
